// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedlookup.sql

package database

import (
	"context"
)

const feedLookup = `-- name: FeedLookup :one
select id, created_at, updated_at, name, url, user_id
from feeds
where url = $1
`

func (q *Queries) FeedLookup(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, feedLookup, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
