// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: following.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const followingLookup = `-- name: FollowingLookup :many
select feeds.name as feed_name, feeds.url as feed_url
from feeds
inner join feed_follows on feeds.id = feed_follows.feed_id
where feed_follows.user_id = $1
`

type FollowingLookupRow struct {
	FeedName string
	FeedUrl  string
}

func (q *Queries) FollowingLookup(ctx context.Context, userID uuid.UUID) ([]FollowingLookupRow, error) {
	rows, err := q.db.QueryContext(ctx, followingLookup, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowingLookupRow
	for rows.Next() {
		var i FollowingLookupRow
		if err := rows.Scan(&i.FeedName, &i.FeedUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
