// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unfollowfeed.sql

package database

import (
	"context"
)

const unfollowFeed = `-- name: UnfollowFeed :exec

delete from feed_follows
where user_id = (select users.id from users where users.name = $1)
and feed_id = (select feeds.id from feeds where feeds.url = $2)
`

type UnfollowFeedParams struct {
	Name string
	Url  string
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.Name, arg.Url)
	return err
}
